#!/usr/bin/env python3
"""Record what the print artifacts currently are, so a rebuild can be diffed.

**Why this file exists.** The generated HTML used to be committed — fifteen
files, eight thousand lines, rewritten by ninety-six commits in three weeks.
Nobody reads it. What it was actually for was the staleness check: rebuild
everything, ask git what moved, and find the card sheet a rules edit quietly
invalidated. Reasoning about which sheets should have moved has failed three
for three; rebuilding and diffing has caught it three for three, so the check
stays and the artifacts go.

This is the replacement. One tracked line per artifact — name, what it holds,
and a hash of its bytes. A rebuild rewrites it, and `git diff` then names
exactly which sheets moved in one line each, which is a signal somebody will
actually read. An eight-thousand-line diff was not.

Usage:
  python3 manifest.py           -> rewrite manifest.txt from the HTML on disk
  python3 manifest.py --print   -> write nothing, print what it would say
"""
import hashlib
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, 'manifest.txt')

# What to count, in order of preference. A card sheet is cards; the character
# handout is sheets; a rules document has neither, so it falls back to its
# section headings, which is the thing that actually moves when rules change.
# Match on the class *prefix*, never the whole attribute. The first version
# of this counted `class="card"` exactly and silently missed the one card
# that carries `class="card dense"` — so the core sheet read 165 when it
# seats 166, and a manifest that miscounts is worse than no manifest.
# Counting the name div rather than the container is also closer to the
# truth: it counts cards, not boxes that happen to hold one.
COUNTERS = (
    ('cards',    r'class="card-name[\s">]'),
    ('sheets',   r'class="sheet[\s">]'),
    ('sections', r'<h2[\s>]'),
    ('pages',    r'class="page[\s">]'),
)


def describe(path):
    raw = open(path, 'rb').read()
    text = raw.decode('utf-8', 'replace')
    for label, pattern in COUNTERS:
        n = len(re.findall(pattern, text))
        if n:
            return f'{n} {label}', hashlib.sha256(raw).hexdigest()[:12]
    return '—', hashlib.sha256(raw).hexdigest()[:12]


def build():
    rows = []
    for name in sorted(os.listdir(HERE)):
        if not name.endswith('.html'):
            continue
        held, digest = describe(os.path.join(HERE, name))
        rows.append((name[:-len('.html')], held, digest))
    width = max((len(r[0]) for r in rows), default=0)
    held_w = max((len(r[1]) for r in rows), default=0)
    lines = [
        '# Print artifacts — what they hold and what they hash to.',
        '# Regenerated by manifest.py; see printing/README.md. The HTML itself',
        '# is build output and is not tracked. A changed hash here means that',
        '# sheet moved and its PDF is stale.',
        '',
    ]
    lines += [f'{n:<{width}}  {h:>{held_w}}  {d}' for n, h, d in rows]
    return '\n'.join(lines) + '\n'


if __name__ == '__main__':
    out = build()
    if '--print' in sys.argv:
        sys.stdout.write(out)
    else:
        open(OUT, 'w').write(out)
        print(f'manifest.txt — {len(out.splitlines()) - 5} artifacts recorded')
