#!/usr/bin/env python3
"""Record what the print artifacts currently are, so a rebuild can be diffed.

**Why this file exists.** The generated HTML used to be committed — fifteen
files, eight thousand lines, rewritten by ninety-six commits in three weeks.
Nobody reads it. What it was actually for was the staleness check: rebuild
everything, ask git what moved, and find the card sheet a rules edit quietly
invalidated. Reasoning about which sheets should have moved has failed three
for three; rebuilding and diffing has caught it three for three, so the check
stays and the artifacts go.

This is the replacement. One tracked line per artifact — name, what it holds,
and a hash of its bytes. A rebuild rewrites it, and `git diff` then names
exactly which sheets moved in one line each, which is a signal somebody will
actually read. An eight-thousand-line diff was not.

Usage:
  python3 manifest.py           -> rewrite manifest.txt from the HTML on disk
  python3 manifest.py --print   -> write nothing, print what it would say
"""
import hashlib
import os
import re
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, 'manifest.txt')

# What to count, in order of preference. A card sheet is cards; the character
# handout is sheets; a rules document has neither, so it falls back to its
# section headings, which is the thing that actually moves when rules change.
# Match on the class *prefix*, never the whole attribute. The first version
# of this counted `class="card"` exactly and silently missed the one card
# that carries `class="card dense"` — so the core sheet read 165 when it
# seats 166, and a manifest that miscounts is worse than no manifest.
# Counting the name div rather than the container is also closer to the
# truth: it counts cards, not boxes that happen to hold one.
COUNTERS = (
    ('cards',    r'class="card-name[\s">]'),
    ('sheets',   r'class="sheet[\s">]'),
    ('sections', r'<h2[\s>]'),
    ('pages',    r'class="page[\s">]'),
)


def describe(path):
    raw = open(path, 'rb').read()
    text = raw.decode('utf-8', 'replace')
    for label, pattern in COUNTERS:
        n = len(re.findall(pattern, text))
        if n:
            return f'{n} {label}', hashlib.sha256(raw).hexdigest()[:12]
    return '—', hashlib.sha256(raw).hexdigest()[:12]


def pool_counts():
    """The one card count in this repo.

    Five prose files used to each state how big the core pool is and they
    disagreed three ways — 163, 164 and 165 — because a number restated in
    five places drifts in five directions. They cite this now. It is computed
    from the card files and the tier lists every time, so it cannot be stale
    and cannot be wrong without the source being wrong.
    """
    sys.path.insert(0, os.path.join(REPO, 'combat-simulations'))
    import cards
    from collections import Counter

    core = cards.core_pool()
    by = Counter(c.color for c in core)
    every = Counter(c.color for c in cards.load())

    bench = 0
    tiers = os.path.join(REPO, 'cards', 'tiers')
    beginner = open(os.path.join(tiers, 'beginner.md')).read()
    for line in beginner.splitlines():
        m = re.match(r'\*\*(?:Red|Blue|Green) \((\d+)\)\.\*\*(.*)', line)
        if m:
            bench += len([n for n in m.group(2).split('·') if n.strip()])

    mid_text = open(os.path.join(tiers, 'middle.md')).read()
    body = mid_text[mid_text.index('## Too strong to start'):mid_text.index('## Notes')]
    middle = len(set(re.findall(r"^\|\s*\*\*([A-Z][A-Z '\-]*?)\*\*\s*\|", body, re.M)))

    colour = by['RED'] + by['BLUE'] + by['GREEN']
    return [
        '## The card count',
        '',
        f"  three colour lists       {colour:>4}   (Red {by['RED']}, Blue {by['BLUE']}, Green {by['GREEN']})",
        f"  colourless                 {by['COLORLESS']:>2}",
        f'  core pool, all four      {len(core):>4}',
        '',
        f'  of the {colour} colour-list cards:',
        f'    seated in a printed set{colour - bench - middle:>4}',
        f'    cleared, on the bench  {bench:>4}',
        f'    middle tier            {middle:>4}',
        '',
        f"  every card in cards/     {sum(every.values()):>4}   "
        f"(Red {every['RED']}, Blue {every['BLUE']}, Green {every['GREEN']}, "
        f"colourless {every['COLORLESS']})",
        '',
    ]


def build():
    rows = []
    for name in sorted(os.listdir(HERE)):
        if not name.endswith('.html'):
            continue
        held, digest = describe(os.path.join(HERE, name))
        rows.append((name[:-len('.html')], held, digest))
    width = max((len(r[0]) for r in rows), default=0)
    held_w = max((len(r[1]) for r in rows), default=0)
    lines = [
        '# Regenerated by printing/manifest.py — see printing/README.md.',
        '# Nothing here is written by hand. This is the only card count in the',
        '# repo; every other file cites it rather than restating a number.',
        '',
    ]
    lines += pool_counts()
    lines += ['## Print artifacts', '',
              '# The HTML is build output and is not tracked. A changed hash',
              '# means that sheet moved and its PDF is stale.', '']
    lines += [f'  {n:<{width}}  {h:>{held_w}}  {d}' for n, h, d in rows]
    return '\n'.join(lines) + '\n'


if __name__ == '__main__':
    out = build()
    if '--print' in sys.argv:
        sys.stdout.write(out)
    else:
        open(OUT, 'w').write(out)
        print(f'manifest.txt — {len(out.splitlines()) - 5} artifacts recorded')
